---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
