apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bjjoKkv3Gw==,iv:tThEMaee8rINpQeDbQGLNAnIrykZlaQ27HMzb+iMcoY=,tag:diQ7HBK6xf1iGzyNmkyTSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMEg4dTVXSlRWN0E4NTNL
            ckFWVm9ybnk1cWdiRzRkaU5FUURNZHMrUVFZCkhQTnhTZHNMQi82QUJuNTVQM2lk
            ZnhBQmhzTTNDdHFmNEp0SjVneXh0M2MKLS0tIGk5c25wYmMxaVJ5N3gyaHQ4ZkU0
            TzVhWEd3QTJnNTNUdGFvVlp1aW1hc1kKpnsHy9PaF01K9OJ+35Efk4QvUOZ0C7a2
            51qSSK/wNJCCcfjLE02pGtvN7Z2emlQg9qrBAvYKA5ZimoiGLbEw8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T07:50:45Z"
    mac: ENC[AES256_GCM,data:YHg10H+5/deEVkVo7s0zA4+1Qk5j0C2pkyMvcjH9+Kewcu7zaifjtyNMK5M9bINdJvcpWSx72bNM+G1Ludbz9YsaZD/ZFRHohe8LcATfhwhk+HiDq1QM/JT4MFGThR52aPvT2rUOxJ/YUTCUSOXI+6CIi2XmZM9JlAmlObXOGXI=,iv:p4MlJMkB99XL3JHaBjR8lUu/3/LccEFznRW5fXAFaoA=,tag:uhQ78BIJIe0LySDXomBHiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
