apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:6omXpgLTT70ODN8sA5YKuwaSwnKONo+QcT/AvSBB3VgOMFNNHg==,iv:b0Uu8ThlFIn6Bb2LWJyHlQfBmVeiYIGlp7dVPYqWG6Q=,tag:gZC8aFy7dxQ9UlIuxti24A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTFB1MzRIRUpsWng1Vzhx
            ZCszZ2NLYUtIOWlkME8xWmsrclZNZGNxdkhRCjVCZVIyYTdGWEZjRHBwaWY0SkVs
            WDBYbzR6SnlrbHNoTmZ4T3pZL0pReWsKLS0tIG1abUQ4R28rd3hXaGM1UjdGT3l6
            RmF3YjFmbEVlY3RtVXVHeGFrV2xZcnMKUcYZyaVDj85LJygN5yycW7ikeAaoTbBB
            CIOxNf9qZLwUnz1yUn3x7EfewGME+zjUMLZM/+KOVvTBRzDNgmEG+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T07:50:45Z"
    mac: ENC[AES256_GCM,data:k602PdwczRmFKf5cy1bacDOiH/J5hS1Qz/fjIrioG+2lezg/o4nPHTJF52HjRu7bra5pQSbAzt2PteVuz+wUTp+rNBQVnOx4Q0hqNRQK0T+ekDCjoJNRLuYq+lGn91GEFdTLpwuyAvYF84M7yN2iIRmViOitMd3fqlvIO4BP9Dg=,iv:XhwA4ioVaFZGzoy1sCRbzjVZnXdNRqZqnHBMrSHysNM=,tag:VI34S4TaqIEEyrK8BnVS0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
