apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:eLdyLaguRXpxyzSp/X9wLdHPWd1gGj4ki/LcZXoHLY+MBdNXGw==,iv:5rB5LJcc+q0LUSjibQBebr9+Q4MzUfcc0RFXK3SKAj8=,tag:JpQueZXE+lFyIKrtFqERBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU2tDSXRPUmNEVHlFSVRZ
            REx6N0t5ZXJ5TUFjdGQ2WitqRGMvR2Y0bVFBCjRSUHgwbW1Ka24zZzEwcjA2VmVV
            Mjl3anQ4bFo0Z1cyc1p1MGJaSHBZaWsKLS0tIG5hZzNlWkJzTWoxeFkxUWxqZDVL
            ZTNVZEhkcDVGU3o0Mml4SzZUWm5UOWsKMizE21O1/f1YCPVDQWIp867chwUqj/j6
            qM1OdlsU8EzSd63XQpNcC0M1dIFBz2dD2w8f+8lAGxvl4Zs8fHFdQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T05:39:36Z"
    mac: ENC[AES256_GCM,data:fPaCmAg/ClQZVjvz+hrsVD2eTn83fphoFsYEyrFB+h98HgwvevuOVm4z3HRKN+rk0IDFpcBjGUu/R+Nw10QLOpG93BIv61E3roWO0JwlAisxSpYRNff3ynX12Eucvq2XjBYEmyYyLCCBqJlxC9ohaQPVyi+69OOrQCTOP8V2ETU=,iv:dh9XNvWIjo/Ox7egtS2uDVxQIv0JqYlfWSYA+TfcNw8=,tag:OTJVg1OIgPoJ7vIlpn0sAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
