apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Bwe2Kx6bTw4wkao=,iv:h9N+5WMILaB+msbEyuqIwT//j0gwTiidvVn/uSUF0aU=,tag:s1OpmHp+hMsiNKF/hpef8g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+OluicnL5gYhoa0GojckNsD6mwZP,iv:BDScc3wsi9bIOFrATGyEYC+LcYbcIrA71rO4wIamIfI=,tag:2Gjl6deDkzIHOiCtqWRi4A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QSxIDqS1OOtanEFS+hicIy67qo7JrokFGLX3/+5V1E5UKBiK,iv:xUKebXdElSdJkLr3VG7+u+BTU9Tfb9Dm3+67vJnA/K0=,tag:0qBNcUm5G+yudMX9sWS62Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZXViQm1RVE9PMjY2WE9K
            K1dYcDVKTGhXY0pPQ2tzQXhqdTl0VFN5eWtZCkNzUVhicldQWWRDR1BwRjBJMWRB
            WG5LVytyWmROaGlzZFhvUTBycWVoWFUKLS0tIDIvTk9McDRGYmVCbTdNOFA3VVpt
            T0RMSU5JMTQxR1l5RFRCZXFDY3YxNk0KvedHdbh8RyDnMwkwzBzGj3p4aEpHlZ3w
            /urZVs09rvJEvfdQDEN7BXb9ve/YtlD2Sv3DBlFcyjAHI2wxlmw3Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T05:39:36Z"
    mac: ENC[AES256_GCM,data:t2ISzdX3oB4u6NFU1xEklXa41Oa7M43fiD3/bRMFbW5xYSXWWKhSz01zYLkxMHVVfxNnloHOvfYzfkFpGlIdcI3fRuZ856UXnolcWyGE6H59McEs/I8HUdDQZr87Z9huVz2dS65Gdaffoar6Puwih1aGQp8jE2k4c/FKMEftiow=,iv:CjbLbviwK+07PuV89QQdar7AueU0TaZqcx54QEjAVfk=,tag:MhJw9C6a0emUpu8WvzQhfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
