---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Seoul"
  KUBE_VIP_ADDR: "192.168.10.88"
  METALLB_LB_RANGE: "192.168.10.90-192.168.10.100"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.90"
  METALLB_INGRESS_ADDR: "192.168.10.91"
