apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:MWym4yOP4kELOgjT58tb/szNaPO4xhndppf+ouAdFEpaUxVn,iv:flFjlLq8e32tbYW2yUSLPF2HnCVX5FTxCcsk5/qFGTs=,tag:+ivdWHb8nJpIqrb3aXMbXg==,type:str]
    credentials.json: ENC[AES256_GCM,data:MKL2I+n1pX3m0YbntFU5FDhbnuS6ujMT5VmCEglgg39Ad4PaA57G8FbixDUhb1PCW+UjQje54rhH7D79lyIQA3sdO4l+JUZtpjLGwyL/r5dHUV9NdPFn2LZxPB8ORMJZJu4ICz44CHoQOD+uvr/5w5LEpNRyyIA5vYunhQIaLJcODVzYHku1lH6rPf3tg3oNm5IqEM1s5pChRQwO4K+QiZ8wgtKro26UAYLGDJMxcw==,iv:xODIKn1m4r/o6tsnPkj5zimbykwrokSWET/BNP03T1A=,tag:0E6GYlHiCCz8Eu2PdWCVpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cwcf0ta7r5qrvx6xsac832g0pm32klpf2xvkaec40fy6d7feyc4qeyxmgw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUcrOUV4SmFyQktaRmpE
            WDBlTjZxMFA5RXNGZ0ZUam5NR25XR3BtVXpJCmZTMzZ1T1Yxd0RMVWo0MDVZeEpI
            TVd5YlRLRGxNTW5YL1F4ay8xMTZ3MzAKLS0tIDJIZEs5c0tZY01TY0lOWTlza0U1
            TjZqbG8walYvNEJXSnEwbUpTNjRyRVEKGksdxrEbMVFRjGjQ/BRSFWUdH3IS9n0S
            qR9eaLUphuWnigenr/rLmH5usew02tnEj20FfpfXVHrHVjwqKsyKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T06:17:20Z"
    mac: ENC[AES256_GCM,data:QGH4dmFR3o0M7lCYfy+FIHXYLaSQqKuFk4qubeJaARu3oMeuuUf4pLMdXffoFCWujFfbstllKsBVCE480/VpbrV1oJJECcYjyNo2Rjb8TVL9iJj0H+E4U+5S7i7WQ8esxRlnpZ6FtIzBsJZ9ZV8YqLlnvHlYjsnQ02ASTXHlQf0=,iv:eb332VvyRcizzvad6BeAsxHJv5fy+uIgbB69/+hXDuA=,tag:25hYXN7IZnF1N+/QS+YBYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
